
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class interface2 extends javax.swing.JFrame {

    /**
     * Creates new form interface2
     */
    static Random rand = new Random();
    
    int clicked1;
    int rand1;
    int turn=2;
    int turn2=2;
    int buttonsq[]={0,0,0,0,0,0,0,0,0};//ussedbuttons
    int arr1[]={0,0,0,0,0,0,0,0,0};//array of x buttons 
    int arr2[]={0,0,0,0,0,0,0,0,0};//array of y buttons
    JButton b[];
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void clear1(){
          turn=2;
          b1.setText("");b1.setBackground(Color.LIGHT_GRAY);
          b2.setText("");b2.setBackground(Color.LIGHT_GRAY);
          b3.setText("");b3.setBackground(Color.LIGHT_GRAY);
          b4.setText("");b4.setBackground(Color.LIGHT_GRAY);
          b5.setText("");b5.setBackground(Color.LIGHT_GRAY);
          b6.setText("");b6.setBackground(Color.LIGHT_GRAY);
          b7.setText("");b7.setBackground(Color.LIGHT_GRAY);
          b8.setText("");b8.setBackground(Color.LIGHT_GRAY);
          b9.setText("");b9.setBackground(Color.LIGHT_GRAY);
          for(int i=0;i<9;i++){
             buttonsq[i]=0;
             arr1[i]=0;
             arr2[i]=0;
          }
        }
    
    void clear2(){
          turn2=2;
          b1.setText("");b1.setBackground(Color.LIGHT_GRAY);
          b2.setText("");b2.setBackground(Color.LIGHT_GRAY);
          b3.setText("");b3.setBackground(Color.LIGHT_GRAY);
          b4.setText("");b4.setBackground(Color.LIGHT_GRAY);
          b5.setText("");b5.setBackground(Color.LIGHT_GRAY);
          b6.setText("");b6.setBackground(Color.LIGHT_GRAY);
          b7.setText("");b7.setBackground(Color.LIGHT_GRAY);
          b8.setText("");b8.setBackground(Color.LIGHT_GRAY);
          b9.setText("");b9.setBackground(Color.LIGHT_GRAY);
          for(int i=0;i<9;i++){
             buttonsq[i]=0;
             arr1[i]=0;
             arr2[i]=0;
          }
           int num= rand.nextInt(10);
           b[num].setText("X");
           turn2++;
          /*jenerate random */
    }
    
    int player1_winning(){
        if(arr1[0]==1&&arr1[1]==1&&arr1[2]==1){b1.setBackground(Color.red);b2.setBackground(Color.red);b3.setBackground(Color.red); return 1;}
        if(arr1[3]==1&&arr1[4]==1&&arr1[5]==1){b4.setBackground(Color.red);b5.setBackground(Color.red);b6.setBackground(Color.red); return 1;}
        if(arr1[6]==1&&arr1[7]==1&&arr1[8]==1){b7.setBackground(Color.red);b8.setBackground(Color.red);b9.setBackground(Color.red); return 1;}
        if(arr1[0]==1&&arr1[3]==1&&arr1[6]==1){b1.setBackground(Color.red);b4.setBackground(Color.red);b7.setBackground(Color.red); return 1;}
        if(arr1[4]==1&&arr1[1]==1&&arr1[7]==1){b5.setBackground(Color.red);b2.setBackground(Color.red);b8.setBackground(Color.red); return 1;}
        if(arr1[5]==1&&arr1[8]==1&&arr1[2]==1){b6.setBackground(Color.red);b9.setBackground(Color.red);b3.setBackground(Color.red); return 1;}
        if(arr1[0]==1&&arr1[4]==1&&arr1[8]==1){b1.setBackground(Color.red);b5.setBackground(Color.red);b9.setBackground(Color.red); return 1;}
        if(arr1[4]==1&&arr1[6]==1&&arr1[2]==1){b5.setBackground(Color.red);b7.setBackground(Color.red);b3.setBackground(Color.red); return 1;}
        return 0;
    }
    
     int player2_win(){
        if(arr2[0]==1&&arr2[1]==1&&arr2[2]==1){b1.setBackground(Color.green);b2.setBackground(Color.green);b3.setBackground(Color.green); return 1;}
        if(arr2[3]==1&&arr2[4]==1&&arr2[5]==1){b4.setBackground(Color.green);b5.setBackground(Color.green);b6.setBackground(Color.green); return 1;}
        if(arr2[6]==1&&arr2[7]==1&&arr2[8]==1){b7.setBackground(Color.green);b8.setBackground(Color.green);b9.setBackground(Color.green); return 1;}
        if(arr2[0]==1&&arr2[3]==1&&arr2[6]==1){b1.setBackground(Color.green);b4.setBackground(Color.green);b7.setBackground(Color.green); return 1;}
        if(arr2[4]==1&&arr2[1]==1&&arr2[7]==1){b5.setBackground(Color.green);b2.setBackground(Color.green);b8.setBackground(Color.green); return 1;}
        if(arr2[5]==1&&arr2[8]==1&&arr2[2]==1){b6.setBackground(Color.green);b9.setBackground(Color.green);b3.setBackground(Color.green); return 1;}
        if(arr2[0]==1&&arr2[4]==1&&arr2[8]==1){b1.setBackground(Color.green);b5.setBackground(Color.green);b9.setBackground(Color.green); return 1;}
        if(arr2[4]==1&&arr2[6]==1&&arr2[2]==1){b5.setBackground(Color.green);b7.setBackground(Color.green);b3.setBackground(Color.green); return 1;}
        return 0;
     }
     
    int checkWin1(int R1,int R2){
        int count=0;
                if(R1==1){JOptionPane.showMessageDialog(rootPane, "         PLAYER1  WON     :)          ");clear1();return 1;}
                if(R2==1){JOptionPane.showMessageDialog(rootPane, "         PLAYER2  WON     :)          ");clear1();return -1;}         
                else {
                for(int i=0;i<9;i++){
                
                    if(buttonsq[i]==1){count++; continue;}
                    else{break;}
                }
                    if(count==9){JOptionPane.showMessageDialog(rootPane, "         TIE!!!        :)          ");clear1();return 0;}
                    else{return 0;}
                }
     }
    
    int checkWin2(int R1,int R2){
        int count=0;
                if(R1==1){JOptionPane.showMessageDialog(rootPane, "         YOU  LOSt        :(          ");clear2();return 10;}
                if(R2==1){JOptionPane.showMessageDialog(rootPane, "         YOU  WON         :)          ");clear2();return -10;}
                else {
                for(int i=0;i<9;i++){
                
                    if(buttonsq[i]==1){count++; continue;}
                    else{break;}
                }
                    if(count==9){JOptionPane.showMessageDialog(rootPane, "         TIE!!!        :)          ");clear2();return 0;}
                    else{return 2;}
                }
              
     }
     
    int max(int n1,int n2){
      if(n1>n2){return n1;}
      else{return n2;}
    }
    int min (int n1,int n2){
      if(n1<n2){return n1;}
      else{return n2;}
    }
     
    void pc_turn(){
        int bscore=-5122158;
        int bmove=0;
        for(int i=0;i<9;i++){
          // if(b[i].getText().compareTo("")==0){score=alphabeta(b[i],12,-255454,25454512,false);}
           if(buttonsq[i]==0){
              int score=alphabeta(b[i],5,-255454,25454512,false);
              if(score>bscore){
                 System.out.println(score);
                 bscore=score;
                 bmove=i;
                }
           }
        }
        turn2++;
        if(b[bmove].getText().compareTo("")==0){
           b[bmove].setText("X");
           buttonsq[bmove]=1;
           arr1[bmove]=1;
           int R1=player1_winning();
           int R2=player2_win();
           int r=checkWin2(R1,R2);
        }
    }

    int alphabeta(JButton buttons,int depth,int alpha,int beta,boolean maxt){ 
       int R1=player1_winning();
       int R2=player2_win();
       int ret= checkWin2(R1,R2);
       int v=ret;
       if(depth==0||ret==10||ret==-10||ret==2){return v;}
       if(maxt){
          v=-25232;
          for(int i=0;i<9;i++){
            if(buttonsq[i]==0){
               v=max(v,alphabeta(b[i],depth-1,alpha,beta,false));
               alpha=max(alpha,v);
               if(alpha>=beta){break;}
            }
          }
         return v;
        }
        else{
          v=25232;
          for(int i=0;i<9;i++){
            if(buttonsq[i]==0){
              v=min(v,alphabeta(b[i],depth-1,alpha,beta,true));
              beta=min(beta,v);
              if(alpha>=beta){break;}
            }
          }
       return v;
       }
    }
    
    public void sth1(JButton button ,int bnu){
        if(buttonsq[bnu]==0){
            if(turn%2==0){
                turn++;
                button.setText("X");
                buttonsq[bnu]=1;
                arr1[bnu]=1;
                int R1=player1_winning();
                int R2=player2_win();
                int r= checkWin1(R1,R2);
            }
            else{
                turn++;
                button.setText("O");
                buttonsq[bnu]=1;
                arr2[bnu]=1;
                int R1=player1_winning();
                int R2=player2_win();
                int r=checkWin1(R1,R2);
            }

        }
    }
     
    public void sth2(JButton button,int bnu){
       if(buttonsq[bnu]==0){
           if(turn2%2!=0){
               turn2++;
               button.setText("O");
               buttonsq[bnu]=1;
               arr2[bnu]=1;
               int R1=player1_winning();
               int R2=player2_win();
               int r=checkWin2(R1,R2);
               pc_turn();
           }
       }
     }
     
    public interface2() {
        super("interface3");
        initComponents();
        setLocationRelativeTo(null);//center
    }
    public interface2(int para){
        super("interface3");
        initComponents();
        setLocationRelativeTo(null);//center
        clicked1=para;
    }
    public interface2(int para,int rand){
        super("interface3");
        initComponents();
        setLocationRelativeTo(null);//center
        clicked1=para;
        this.b = new JButton[]{b1, b2, b3, b4, b5, b6, b7, b8, b9};
        rand1=rand;
        b[rand1].setText("X");
        buttonsq[rand1]=1;
        arr1[rand1]=1;
        turn2++;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        clearb = new javax.swing.JButton();
        back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("Tic Tac Toe");

        b1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 48)); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        clearb.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        clearb.setText("Clear");
        clearb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbActionPerformed(evt);
            }
        });

        back1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        back1.setText("Go Back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(clearb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(b8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(b7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(clearb, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b2,1);}
        if(clicked1==2){sth2(b2,1);}
    }//GEN-LAST:event_b2ActionPerformed

    private void clearbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbActionPerformed
        // TODO add your handling code here:
       if(clicked1==1){ clear1();}
       if(clicked1==2){clear2();}
    }//GEN-LAST:event_clearbActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b1,0);}
        if(clicked1==2){sth2(b1,0);}
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b3,2);}
        if(clicked1==2){sth2(b3,2);}
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b4,3);}
        if(clicked1==2){sth2(b4,3);}
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b5,4);}
        if(clicked1==2){sth2(b5,4);}
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b6,5);}
        if(clicked1==2){sth2(b6,5);}
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b7,6);}
        if(clicked1==2){sth2(b7,6);}
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b8,7);}
        if(clicked1==2){sth2(b8,7);}
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(clicked1==1){sth1(b9,8);}
        if(clicked1==2){sth2(b9,8);}
    }//GEN-LAST:event_b9ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
         if (clicked1==2||clicked1==3||clicked1==3) {this.hide();new interface3().setVisible(true);}
         if (clicked1==1) {this.hide();interface1 int1=new interface1();int1.setvisible(true);}
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton back1;
    private javax.swing.JButton clearb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
